import { useMemo, useState } from 'react';
import { Bell, BookOpen, CalendarClock, CalendarDays, Check, ChevronDown, Clock3, Flame, LayoutDashboard, Menu, MoreHorizontal, Plus, Settings, Sparkles, Target, TrendingUp, X, LogOut, Timer } from 'lucide-react';
import type { Account } from './Auth';
import { Area, AreaChart, ResponsiveContainer, Tooltip } from 'recharts';
import { activity, chapters, tasks as initialTasks } from './data';

const trend = [{d:'M',v:2.2},{d:'T',v:3.6},{d:'W',v:2.8},{d:'T',v:4.8},{d:'F',v:3.9},{d:'S',v:5.7},{d:'S',v:4.6}];
const nav = [[LayoutDashboard,'Overview'],[Check,'My Tasks'],[CalendarDays,'Planner'],[Timer,'Focus Tools'],[Sparkles,'AI Study Assistant'],[BookOpen,'Full Syllabus'],[Target,'Mock Tests'],[CalendarClock,'Personal Time Table']];

export default function App({ account, onLogout }: { account: Account; onLogout: () => void }){
 const [open,setOpen]=useState(false),[tasks,setTasks]=useState(initialTasks),[modal,setModal]=useState(false);
 const complete=(i:number)=>setTasks(t=>t.map((x,n)=>n===i?{...x,done:100}:x));
 const progress=useMemo(()=>Math.round(tasks.reduce((a,t)=>a+t.done,0)/tasks.length),[tasks]);
 return <div className="app dark">
  <aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark">J</span><span>JEE <b>Blueprint</b></span><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div>
   <div className="profile"><div className="avatar">{account.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{account.name}</strong><small>JEE 2026 Aspirant</small></div><ChevronDown size={15}/></div>
   <nav>{nav.map(([Icon,label],i)=><a className={i===0?'active':''} href="#" key={String(label)}><Icon size={19}/>{String(label)}</a>)}</nav><p className="nav-label">ORGANIZE</p><nav><a href="#"><Clock3 size={19}/>Revision queue <em>5</em></a><a href="#"><Sparkles size={19}/>Formula book</a><a href="#"><TrendingUp size={19}/>Analytics</a></nav>
   <div className="sidebar-bottom"><a href="#"><Settings size={19}/>Settings</a><button className="logout" onClick={onLogout}><LogOut size={18}/>Log out</button><div className="upgrade"><Sparkles size={17}/><b>Unlock your potential</b><small>Build a better study habit.</small><button>Explore Pro</button></div></div>
  </aside>
  {!open && <button className="mobile-menu-toggle" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={19}/></button>}
  <main><header><div className="crumb">Dashboard <span>/</span> Overview</div><div className="header-actions"><button className="icon notify"><Bell/><i/></button><button className="new-task" onClick={()=>setModal(true)}><Plus size={18}/>New task</button></div></header>
   <section className="welcome"><div><p className="eyebrow">SUNDAY, 12 JULY</p><h1>Good morning, {account.name.split(' ')[0]} <span>✦</span></h1><p>Small steps today create big results tomorrow.</p></div><div className="countdown"><div><small>JEE MAIN 2026</small><b>180 <span>days to go</span></b></div><Target/></div></section>
   <section className="stats"><Stat icon={<Flame/>} label="Study streak" value="7 days" extra="Personal best: 12" color="orange"/><Stat icon={<Clock3/>} label="Focus time" value="3h 42m" extra="of 6h daily goal" color="blue"/><Stat icon={<Target/>} label="Today's progress" value={progress+'%'} extra="3 of 5 tasks done" color="violet"/><Stat icon={<TrendingUp/>} label="Overall readiness" value="68%" extra="↑ 4% this month" color="green"/></section>
   <section className="grid top-grid"><div className="card focus"><div className="card-title"><div><p className="eyebrow">TODAY'S FOCUS</p><h2>Your study plan</h2></div><button className="link">View planner <span>→</span></button></div><div className="task-list">{tasks.map((t,i)=><div className="task" key={t.title}><button aria-label="complete task" className={t.done===100?'check checked':'check'} onClick={()=>complete(i)}>{t.done===100&&<Check size={13}/>}</button><div className={'subject-dot '+t.tone}/><div className="task-copy"><b>{t.title}</b><small>{t.subject} · {t.time}</small></div><div className="task-progress"><span>{t.done}%</span><div><i style={{width:t.done+'%'}}/></div></div><button className="more"><MoreHorizontal/></button></div>)}</div><button className="add-inline" onClick={()=>setModal(true)}><Plus size={17}/> Add a task</button></div>
    <div className="card goal"><div className="card-title"><div><p className="eyebrow">WEEKLY GOAL</p><h2>Make it count</h2></div><MoreHorizontal/></div><div className="circle"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="48"/><circle className="ring" cx="60" cy="60" r="48"/></svg><div><b>62%</b><small>18.5 / 30 hrs</small></div></div><p>You’re <b>on track!</b> Just 11.5 hrs to go.</p><div className="goal-bar"><i/></div></div></section>
   <section className="grid bottom-grid"><div className="card chart"><div className="card-title"><div><p className="eyebrow">STUDY RHYTHM</p><h2>Focus time</h2></div><button className="select">This week <ChevronDown size={14}/></button></div><div className="chart-number"><b>24.8h</b><span>↑ 18% vs last week</span></div><div className="graph"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#8b5cf6" stopOpacity=".3"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e8e4f0'}}/><Area type="monotone" dataKey="v" stroke="#7c5cf1" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div><div className="days">{trend.map(x=><span key={x.d}>{x.d}</span>)}</div></div>
   <div className="card chapters"><div className="card-title"><div><p className="eyebrow">CHAPTER TRACKER</p><h2>Keep moving forward</h2></div><button className="link">See all <span>→</span></button></div>{chapters.map(([name,sub,p])=><div className="chapter" key={name as string}><div><b>{name}</b><small>{sub}</small></div><div className="thin"><i style={{width:p+'%'}}/></div><strong>{p}%</strong></div>)}</div>
   <div className="card activity"><div className="card-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Momentum matters</h2></div></div>{activity.map((a,i)=><div className="event" key={a}><span className={'event-icon e'+i}>{i===0?<Check/>:i===1?<BookOpen/>:<Flame/>}</span><p>{a}<small>{i===0?'2 hours ago':i===1?'Yesterday': '2 days ago'}</small></p></div>)}</div></section>
  </main>{modal&&<TaskModal close={()=>setModal(false)} add={(title)=>{setTasks(t=>[...t,{title,subject:'General',time:'1h',done:0,tone:'blue'}]);setModal(false)}}/>}</div>
}
function Stat({icon,label,value,extra,color}:{icon:React.ReactNode,label:string,value:string,extra:string,color:string}){return <div className="stat card"><span className={'stat-icon '+color}>{icon}</span><p>{label}</p><h2>{value}</h2><small>{extra}</small></div>}
function TaskModal({close,add}:{close:()=>void,add:(x:string)=>void}){const [title,setTitle]=useState('');return <div className="backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();if(title.trim())add(title)}}><button type="button" className="modal-close" onClick={close}><X/></button><p className="eyebrow">PLAN YOUR DAY</p><h2>Add a new task</h2><label>Task title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Solve 30 Mechanics PYQs"/></label><label>Subject<select><option>Physics</option><option>Chemistry</option><option>Mathematics</option></select></label><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="new-task">Create task</button></div></form></div>}
