import { useEffect, useMemo, useState } from 'react';
import { Bell, BookOpen, CalendarClock, Check, ChevronDown, Clock3, Flame, LayoutDashboard, Menu, MoreHorizontal, Plus, Settings, Sparkles, Target, TrendingUp, X, LogOut, Timer } from 'lucide-react';
import type { Account } from './Auth';
import { request } from './Auth';
import { Area, AreaChart, ResponsiveContainer, Tooltip } from 'recharts';
import { activity, chapters } from './data';

type DashboardTask = { id: number; title: string; subject: string; estimated_minutes: number; progress: number; status: string };

const trend = [{d:'M',v:2.2},{d:'T',v:3.6},{d:'W',v:2.8},{d:'T',v:4.8},{d:'F',v:3.9},{d:'S',v:5.7},{d:'S',v:4.6}];
const nav = [[LayoutDashboard,'Overview'],[Check,'My Tasks'],[Timer,'Focus Tools'],[Sparkles,'AI Study Assistant'],[BookOpen,'Full Syllabus'],[CalendarClock,'Personal Time Table']];
const toneFor = (subject: string) => subject === 'Physics' ? 'blue' : subject === 'Chemistry' ? 'violet' : subject === 'Mathematics' ? 'amber' : 'blue';

// Placeholder links to features that aren't built yet — prevented from navigating/jumping
// the page, with a "coming soon" hint, instead of silently doing nothing or scroll-jumping.
const comingSoon = (event: { preventDefault: () => void }) => event.preventDefault();

export default function App({ account, onLogout }: { account: Account; onLogout: () => void }){
 const [open,setOpen]=useState(false),[modal,setModal]=useState(false);
 const [tasks,setTasks]=useState<DashboardTask[]>([]);
 const loadTasks = () => { request('/tasks?status=pending').then(({ tasks }) => setTasks(tasks.slice(0, 5))).catch(() => {}); };
 useEffect(loadTasks, []);
 const complete=async(task:DashboardTask)=>{ const nextStatus = task.status==='completed' ? 'pending' : 'completed'; const body:{status:string;progress?:number}={status:nextStatus}; if(nextStatus==='completed')body.progress=100; try { await request(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify(body)}); loadTasks(); } catch { /* ignore — dashboard glance widget, full errors surface on the Tasks page */ } };
 const progress=useMemo(()=>tasks.length?Math.round(tasks.reduce((a,t)=>a+t.progress,0)/tasks.length):0,[tasks]);
 return <div className="app dark">
  <aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark">J</span><span>JEE <b>Blueprint</b></span><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div>
   <button className="profile" onClick={comingSoon} title="Account menu — coming soon"><div className="avatar">{account.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{account.name}</strong><small>JEE 2026 Aspirant</small></div><ChevronDown size={15}/></button>
   <nav>{nav.map(([Icon,label],i)=><a className={i===0?'active':''} href="#" key={String(label)} onClick={label==='My Tasks'?(e)=>{e.preventDefault();document.getElementById('tasks')?.scrollIntoView({behavior:'smooth'});}:undefined}><Icon size={19}/>{String(label)}</a>)}</nav><p className="nav-label">ORGANIZE</p><nav><a href="#" onClick={comingSoon} title="Coming soon"><Clock3 size={19}/>Revision queue <em>5</em></a><a href="#" onClick={comingSoon} title="Coming soon"><Sparkles size={19}/>Formula book</a><a href="#" onClick={comingSoon} title="Coming soon"><TrendingUp size={19}/>Analytics</a></nav>
   <div className="sidebar-bottom"><a href="#" onClick={comingSoon} title="Coming soon"><Settings size={19}/>Settings</a><button className="logout" onClick={onLogout}><LogOut size={18}/>Log out</button><div className="upgrade"><Sparkles size={17}/><b>Unlock your potential</b><small>Build a better study habit.</small><button onClick={comingSoon} title="Coming soon">Explore Pro</button></div></div>
  </aside>
  {!open && <button className="mobile-menu-toggle" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={19}/></button>}
  <main><header><div className="crumb">Dashboard <span>/</span> Overview</div><div className="header-actions"><button className="icon notify" onClick={comingSoon} title="Coming soon"><Bell/><i/></button><button className="new-task" onClick={()=>setModal(true)}><Plus size={18}/>New task</button></div></header>
   <section className="welcome"><div><p className="eyebrow">SUNDAY, 12 JULY</p><h1>Good morning, {account.name.split(' ')[0]} <span>✦</span></h1><p>Small steps today create big results tomorrow.</p></div><div className="countdown"><div><small>JEE MAIN 2026</small><b>180 <span>days to go</span></b></div><Target/></div></section>
   <section className="stats"><Stat icon={<Flame/>} label="Study streak" value="7 days" extra="Personal best: 12" color="orange"/><Stat icon={<Clock3/>} label="Focus time" value="3h 42m" extra="of 6h daily goal" color="blue"/><Stat icon={<Target/>} label="Today's progress" value={progress+'%'} extra="3 of 5 tasks done" color="violet"/><Stat icon={<TrendingUp/>} label="Overall readiness" value="68%" extra="↑ 4% this month" color="green"/></section>
   <section className="grid top-grid"><div className="card focus"><div className="card-title"><div><p className="eyebrow">TODAY'S FOCUS</p><h2>Your study plan</h2></div><button className="link" onClick={()=>document.getElementById('planner')?.scrollIntoView({behavior:'smooth'})}>View planner <span>→</span></button></div><div className="task-list">{tasks.length===0 ? <p className="tasks-empty">No pending tasks — nice work. <a href="#" onClick={(e)=>{e.preventDefault();setModal(true);}}>Add one</a> to plan ahead.</p> : tasks.map((t)=><div className="task" key={t.id}><button aria-label="complete task" className={t.status==='completed'?'check checked':'check'} onClick={()=>complete(t)}>{t.status==='completed'&&<Check size={13}/>}</button><div className={'subject-dot '+toneFor(t.subject)}/><div className="task-copy"><b>{t.title}</b><small>{t.subject} · {t.estimated_minutes} min</small></div><div className="task-progress"><span>{t.progress}%</span><div><i style={{width:t.progress+'%'}}/></div></div><button className="more" onClick={comingSoon} title="Coming soon"><MoreHorizontal/></button></div>)}</div><button className="add-inline" onClick={()=>setModal(true)}><Plus size={17}/> Add a task</button></div>
    <div className="card goal"><div className="card-title"><div><p className="eyebrow">WEEKLY GOAL</p><h2>Make it count</h2></div><MoreHorizontal/></div><div className="circle"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="48"/><circle className="ring" cx="60" cy="60" r="48"/></svg><div><b>62%</b><small>18.5 / 30 hrs</small></div></div><p>You’re <b>on track!</b> Just 11.5 hrs to go.</p><div className="goal-bar"><i/></div></div></section>
   <section className="grid bottom-grid"><div className="card chart"><div className="card-title"><div><p className="eyebrow">STUDY RHYTHM</p><h2>Focus time</h2></div><button className="select" onClick={comingSoon} title="Coming soon">This week <ChevronDown size={14}/></button></div><div className="chart-number"><b>24.8h</b><span>↑ 18% vs last week</span></div><div className="graph"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#8b5cf6" stopOpacity=".3"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e8e4f0'}}/><Area type="monotone" dataKey="v" stroke="#7c5cf1" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div><div className="days">{trend.map((x,i)=><span key={i}>{x.d}</span>)}</div></div>
   <div className="card chapters"><div className="card-title"><div><p className="eyebrow">CHAPTER TRACKER</p><h2>Keep moving forward</h2></div><button className="link" onClick={()=>{window.location.hash='syllabus';}}>See all <span>→</span></button></div>{chapters.map(([name,sub,p])=><div className="chapter" key={name as string}><div><b>{name}</b><small>{sub}</small></div><div className="thin"><i style={{width:p+'%'}}/></div><strong>{p}%</strong></div>)}</div>
   <div className="card activity"><div className="card-title"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Momentum matters</h2></div></div>{activity.map((a,i)=><div className="event" key={a}><span className={'event-icon e'+i}>{i===0?<Check/>:i===1?<BookOpen/>:<Flame/>}</span><p>{a}<small>{i===0?'2 hours ago':i===1?'Yesterday': '2 days ago'}</small></p></div>)}</div></section>
  </main>{modal&&<TaskModal close={()=>setModal(false)} add={async(title,subject)=>{try{await request('/tasks',{method:'POST',body:JSON.stringify({title,subject})});loadTasks();}finally{setModal(false);}}}/>}</div>
}
function Stat({icon,label,value,extra,color}:{icon:React.ReactNode,label:string,value:string,extra:string,color:string}){return <div className="stat card"><span className={'stat-icon '+color}>{icon}</span><p>{label}</p><h2>{value}</h2><small>{extra}</small></div>}
function TaskModal({close,add}:{close:()=>void,add:(title:string,subject:string)=>void}){const [title,setTitle]=useState('');const [subject,setSubject]=useState('Physics');return <div className="backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();if(title.trim())add(title,subject)}}><button type="button" className="modal-close" onClick={close}><X/></button><p className="eyebrow">PLAN YOUR DAY</p><h2>Add a new task</h2><label>Task title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Solve 30 Mechanics PYQs"/></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Physics</option><option>Chemistry</option><option>Mathematics</option></select></label><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="new-task">Create task</button></div></form></div>}
