import { useEffect, useRef, useState } from 'react';
import { Coffee, Pause, Play, RotateCcw, Settings2, Timer, Trophy } from 'lucide-react';

type Tool = 'timer' | 'stopwatch' | 'pomodoro';
const pad = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;

export default function FocusTools() {
  const [tool, setTool] = useState<Tool>('pomodoro');
  const [timerMinutes, setTimerMinutes] = usePersisted('focus-countdown-minutes', 60);
  const [pomodoroWork, setPomodoroWork] = usePersisted('focus-work-minutes', 50);
  const [pomodoroBreak, setPomodoroBreak] = usePersisted('focus-break-minutes', 10);
  return <section className="focus-tools" id="focus-tools"><div className="focus-heading"><div><p className="eyebrow">FOCUS TOOLS</p><h1>Study with intention</h1><p>Choose a method, set a duration, and keep your attention on one block at a time.</p></div><div className="focus-quote"><Trophy/><span>Consistency beats intensity.</span></div></div><div className="tool-tabs">{([['pomodoro','Pomodoro'],['timer','Study timer'],['stopwatch','Stopwatch']] as [Tool,string][]).map(([id,label])=><button className={tool===id?'active':''} key={id} onClick={()=>setTool(id)}>{id==='pomodoro'?<Coffee/>:id==='timer'?<Timer/>:<Trophy/>}{label}</button>)}</div>{tool==='timer'?<Countdown minutes={timerMinutes} setMinutes={setTimerMinutes}/>:tool==='stopwatch'?<Stopwatch/>:<Pomodoro work={pomodoroWork} breakMinutes={pomodoroBreak} setWork={setPomodoroWork} setBreak={setPomodoroBreak}/>}</section>;
}
function Countdown({minutes,setMinutes}:{minutes:number;setMinutes:(n:number)=>void}) { const [seconds,setSeconds]=useState(minutes*60),[running,setRunning]=useState(false); useEffect(()=>{if(!running)setSeconds(minutes*60)},[minutes,running]); useTick(running,()=>setSeconds(value=>{if(value<=1){setRunning(false);return 0}return value-1})); return <ToolCard eyebrow="CUSTOM COUNTDOWN" title="Set your study block" seconds={seconds} running={running} start={()=>setRunning(value=>!value)} reset={()=>{setRunning(false);setSeconds(minutes*60)}}><div className="duration-settings"><label>Minutes<input type="number" min="1" max="360" value={minutes} onChange={e=>setMinutes(limit(e.target.value,1,360))}/></label><p>Choose the length of one focused study block. The timer pauses at zero.</p></div></ToolCard> }
function Stopwatch(){const [seconds,setSeconds]=useState(0),[running,setRunning]=useState(false);useTick(running,()=>setSeconds(value=>value+1));return <ToolCard eyebrow="OPEN STUDY SESSION" title="Track uninterrupted focus" seconds={seconds} running={running} start={()=>setRunning(value=>!value)} reset={()=>{setRunning(false);setSeconds(0)}}><div className="tool-note"><Trophy/><p>Use this when the task matters more than the clock. Pause only for a real break.</p></div></ToolCard>}
function Pomodoro({work,breakMinutes,setWork,setBreak}:{work:number;breakMinutes:number;setWork:(n:number)=>void;setBreak:(n:number)=>void}){const [mode,setMode]=useState<'work'|'break'>('work'),[seconds,setSeconds]=useState(work*60),[running,setRunning]=useState(false),[rounds,setRounds]=useState(0);const activeMinutes=mode==='work'?work:breakMinutes;useEffect(()=>{if(!running)setSeconds(activeMinutes*60)},[activeMinutes,mode,running]);useTick(running,()=>setSeconds(value=>{if(value<=1){const next=mode==='work'?'break':'work';if(mode==='work')setRounds(r=>r+1);setMode(next);return (next==='work'?work:breakMinutes)*60}return value-1}));return <ToolCard eyebrow={mode==='work'?'POMODORO · FOCUS':'POMODORO · BREAK'} title={mode==='work'?'Deep work session':'Recover, then return'} seconds={seconds} running={running} start={()=>setRunning(value=>!value)} reset={()=>{setRunning(false);setSeconds(activeMinutes*60)}} extra={<span className="round-count">{rounds} focus rounds finished</span>}><div className="duration-settings two"><label>Focus minutes<input type="number" min="5" max="120" value={work} onChange={e=>setWork(limit(e.target.value,5,120))}/></label><label>Break minutes<input type="number" min="1" max="60" value={breakMinutes} onChange={e=>setBreak(limit(e.target.value,1,60))}/></label><p>After each focus block, the timer automatically changes to a break. It then returns to focus.</p></div></ToolCard>}
function ToolCard({eyebrow,title,seconds,running,start,reset,children,extra}:{eyebrow:string;title:string;seconds:number;running:boolean;start:()=>void;reset:()=>void;children:React.ReactNode;extra?:React.ReactNode}){return <div className="tool-card"><div className="tool-card-copy"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{extra}<div className="tool-display"><b>{pad(seconds)}</b><span>{running?'Focus in progress':'Ready when you are'}</span></div><div className="tool-actions"><button className="start-focus" onClick={start}>{running?<><Pause/> Pause</>:<><Play/> Start</>}</button><button className="reset-focus" onClick={reset}><RotateCcw/> Reset</button></div></div><div className="tool-settings"><Settings2/><h3>Customize</h3>{children}</div></div>}
function useTick(running:boolean,callback:()=>void){const saved=useRef(callback);useEffect(()=>{saved.current=callback},[callback]);useEffect(()=>{if(!running)return;const interval=window.setInterval(()=>saved.current(),1000);return()=>window.clearInterval(interval)},[running])}
function usePersisted(key:string,initial:number):[number,(value:number)=>void]{const [value,setValue]=useState(()=>Number(localStorage.getItem(key))||initial);const update=(next:number)=>{setValue(next);localStorage.setItem(key,String(next))};return[value,update]}
function limit(value:string,min:number,max:number){return Math.max(min,Math.min(max,Number(value)||min))}
