import { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, CircleCheck, Clock3, Target } from 'lucide-react';

const physics = ['Newton’s Laws of Motion', 'Rotational Motion', 'Thermodynamics', 'Kinetic Theory & Thermal Properties', 'Oscillations', 'Waves', 'Capacitance', 'Current Electricity', 'Moving Charges & Magnetism', 'Magnetism and Matter', 'EMI & AC', 'Ray Optics', 'Wave Optics', 'Modern Physics', 'Semiconductors'];
const chemistry = ['Electrochemistry', 'Chemical Kinetics', 'Thermodynamics', 'Equilibrium', 'Class 12 Organic: current topic', 'P-Block Elements', 'D- and F-Block Elements', 'Salt Analysis', 'Physical Chemistry mixed PYQs'];
const maths = ['Applications of Derivatives', 'Quadratic Equations', 'Complex Numbers', 'Vector Algebra', '3D Geometry', 'Inverse Trigonometric Functions', 'Integration', 'Differential Equations', 'Probability', 'Permutations & Combinations', 'Binomial Theorem', 'Sequence & Series', 'Circle', 'Conic Sections'];
const weekdays = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const actions = ['concept repair + Level 1 questions', 'timed practice set', 'JEE Main PYQ drill', 'error-correction and reattempt'];
const localDay = (date: Date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());
const key = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const add = (date: Date, amount: number) => { const copy = new Date(date); copy.setDate(copy.getDate() + amount); return copy; };
const phase = (week: number) => week <= 4 ? 'Foundation recovery' : week <= 8 ? 'Mains output' : 'Advanced strengthening';

export default function Planner(){
 const start = useMemo(() => localDay(new Date()), []); const end = useMemo(() => new Date(start.getFullYear(), 11, 31), [start]); const [selected,setSelected] = useState(start); const [month,setMonth] = useState(new Date(start.getFullYear(), start.getMonth(), 1)); const [done,setDone] = useState<string[]>(() => JSON.parse(localStorage.getItem('jee-plan-complete') || '[]'));
 const index = Math.max(0, Math.floor((localDay(selected).getTime()-start.getTime())/86400000)); const week = Math.floor(index/7)+1; const schedule = buildSchedule(selected,index,week); const first = new Date(month.getFullYear(),month.getMonth(),1); const offset = first.getDay(); const days = Array.from({length:42},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i-offset+1));
 const toggle = (id:string) => setDone(old => { const updated = old.includes(id) ? old.filter(x=>x!==id) : [...old,id]; localStorage.setItem('jee-plan-complete',JSON.stringify(updated)); return updated; });
 return <section className="planner-page" id="planner"><div className="planner-heading"><div><p className="eyebrow">FIVE-MONTH PERSONAL PLANNER</p><h1>Every day has a purpose</h1><p>Select any date through 31 December to see its distinct preparation and revision plan. The sequence advances instead of repeating a fixed week.</p></div><div className="planner-phase"><Target/><div><small>SELECTED WEEK</small><b>Week {week}</b><span>{phase(week)}</span></div></div></div><div className="planner-layout"><aside className="calendar-card"><div className="calendar-title"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><b>{month.toLocaleString('default',{month:'long',year:'numeric'})}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="calendar-weekdays">{weekdays.map(d=><span key={d}>{d}</span>)}</div><div className="calendar-days">{days.map(day=>{const inMonth=day.getMonth()===month.getMonth(), selectedDay=key(day)===key(selected), active=day>=start&&day<=end;return <button key={key(day)} disabled={!active} className={`${!inMonth?'outside':''} ${selectedDay?'chosen':''} ${active?'planned':''}`} onClick={()=>setSelected(day)}>{day.getDate()}</button>})}</div><p className="calendar-note"><i/> Planned dates · through 31 December</p></aside><div className="day-plan"><div className="day-plan-title"><div><p className="eyebrow">{selected.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</p><h2>{schedule.label}</h2></div><button onClick={()=>{setSelected(start);setMonth(new Date(start.getFullYear(),start.getMonth(),1))}}>Today</button></div><div className="plan-blocks">{schedule.blocks.map(block=>{const id=`${key(selected)}-${block.time}`;return <article key={id} className={'plan-block '+block.kind}><button className={done.includes(id)?'plan-check checked':'plan-check'} onClick={()=>toggle(id)}>{done.includes(id)&&<CircleCheck size={14}/>}</button><time>{block.time}</time><div><span>{block.type}</span><h3>{block.title}</h3><p>{block.note}</p></div></article>})}</div></div></div><div className="planner-principles"><article><Clock3/><div><b>Never repeat blindly</b><span>Each day advances a chapter/action sequence and creates a specific revision target.</span></div></article><article><CalendarDays/><div><b>Revision is scheduled</b><span>Day 1, 3, 7 and 21 reviews are embedded in evening blocks.</span></div></article><article><Target/><div><b>Sunday is feedback day</b><span>Tests and analysis replace normal afternoon study to improve accuracy.</span></div></article></div></section>
}
function buildSchedule(date:Date,index:number,week:number){const p=physics[index%physics.length], c=chemistry[Math.floor(index/2)%chemistry.length], m=maths[Math.floor((index+1)/2)%maths.length], action=actions[Math.floor(index/physics.length)%actions.length], revisionIndex=Math.max(0,index-3), revision=physics[revisionIndex%physics.length];const sunday=date.getDay()===0;return {label:sunday?'Mock, analysis & recovery':'Focused preparation day',blocks:sunday?[{time:'8:00–11:00',type:'Mock test',title:'JEE Main part/full mock',note:'Use the current syllabus; focus on accuracy before speed.',kind:'mock'},{time:'12:00–2:30',type:'Analysis',title:'Classify every wrong or skipped question',note:'Concept gap, calculation, silly mistake, time issue, or guess.',kind:'revision'},{time:'4:00–5:30',type:'Backlog repair',title:`${p} — weakest question set`,note:'Reattempt errors only; do not add new lectures.',kind:'prep'},{time:'10:45–12:15',type:'Weekly revision',title:'Formulae, reactions & error notebook',note:'Prepare the next week’s priority list.',kind:'revision'}]:[{time:'7:30–9:15',type:'Physics preparation',title:`${p} — ${action}`,note:'20–30 deliberate questions; record every repeated mistake.',kind:'prep'},{time:'3:30–5:15',type:index%2?'Chemistry preparation':'Maths preparation',title:index%2?`${c} — timed practice + NCERT review`:`${m} — focused problem set`,note:'Do not switch chapters until this block is complete.',kind:'prep'},{time:'6:00–10:00',type:'Coaching',title:'PW Lakshya live classes',note:'Attend live; make a short doubt/error list.',kind:'coaching'},{time:'10:45–12:15',type:'Spaced revision',title:`Revise ${revision} (Day 3 / 7 / 21 cycle)`,note:'Formula recall, 10 PYQs, and reattempt difficult errors.',kind:'revision'},{time:'12:15–1:00',type:'Closure',title:'Error notebook & next-day setup',note:'Write only high-value mistakes and sleep by 1 AM.',kind:'closure'}]}}
