import { FormEvent, useEffect, useState } from 'react';
import { Check, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { request } from './Auth';

type Task = { id: number; title: string; subject: string; chapter: string; priority: string; estimated_minutes: number; status: string; deadline: string; progress: number; notes: string; recurrence: string };
const blank = { title: '', subject: 'Physics', chapter: '', priority: 'medium', estimated_minutes: 60, deadline: '', notes: '', recurrence: 'none' };

export default function Tasks() {
  const [tasks, setTasks] = useState<Task[]>([]), [filter, setFilter] = useState('pending'), [search, setSearch] = useState(''), [editing, setEditing] = useState<Partial<Task> | null>(null), [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); request(`/tasks?status=${filter}&search=${encodeURIComponent(search)}`).then(({ tasks }) => setTasks(tasks)).finally(() => setLoading(false)); };
  useEffect(load, [filter, search]);
  const save = async (values: Partial<Task>) => { const isEdit = Boolean(values.id); const result = await request(isEdit ? `/tasks/${values.id}` : '/tasks', { method: isEdit ? 'PATCH' : 'POST', body: JSON.stringify(values) }); setEditing(null); isEdit ? setTasks(list => list.map(item => item.id === result.task.id ? result.task : item)) : load(); };
  const complete = async (task: Task) => { const result = await request(`/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: task.status === 'completed' ? 'pending' : 'completed', progress: task.status === 'completed' ? 0 : 100 }) }); setTasks(list => list.map(item => item.id === task.id ? result.task : item)); };
  const remove = async (id: number) => { if (!window.confirm('Delete this task?')) return; await request(`/tasks/${id}`, { method: 'DELETE' }); setTasks(list => list.filter(task => task.id !== id)); };
  return <section className="tasks-page" id="tasks"><div className="tasks-heading"><div><p className="eyebrow">PERSONAL TASK SYSTEM</p><h1>Study tasks</h1><p>Turn today’s study intentions into focused, finishable work.</p></div><button className="task-create" onClick={() => setEditing(blank)}><Plus size={17}/> Create task</button></div><div className="task-controls"><div className="task-filters">{['pending', 'completed', 'archived', 'all'].map(status => <button key={status} className={filter === status ? 'active' : ''} onClick={() => setFilter(status)}>{status}</button>)}</div><label className="task-search"><Search size={16}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tasks"/></label></div>{loading ? <p className="tasks-empty">Loading your tasks…</p> : <div className="task-board">{tasks.map(task => <article className="saved-task" key={task.id}><button className={task.status === 'completed' ? 'saved-check done' : 'saved-check'} onClick={() => complete(task)}>{task.status === 'completed' && <Check size={14}/>}</button><div className="saved-task-copy"><div><span className={'priority '+task.priority}>{task.priority}</span><small>{task.subject}{task.chapter && ` · ${task.chapter}`}</small></div><h3>{task.title}</h3><p>{task.estimated_minutes} min {task.deadline && ` · Due ${task.deadline}`}</p></div><div className="saved-actions"><button onClick={() => setEditing(task)} aria-label="edit task"><Pencil size={15}/></button><button onClick={() => remove(task.id)} aria-label="delete task"><Trash2 size={15}/></button></div></article>)}</div>}{!loading && tasks.length === 0 && <div className="tasks-empty"><p>No {filter === 'all' ? '' : filter} tasks yet.</p><button onClick={() => setEditing(blank)}>Create your first task</button></div>}{editing && <Editor task={editing} close={() => setEditing(null)} save={save}/>}</section>;
}
function Editor({ task, close, save }: { task: Partial<Task>; close: () => void; save: (task: Partial<Task>) => Promise<void> }) { const [form, setForm] = useState(task); const [saving, setSaving] = useState(false); const change = (key: string, value: string | number) => setForm(current => ({ ...current, [key]: value })); const submit = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { await save(form); } finally { setSaving(false); } }; return <div className="task-backdrop"><form className="task-editor" onSubmit={submit}><button className="editor-close" type="button" onClick={close}><X/></button><p className="eyebrow">{task.id ? 'EDIT TASK' : 'NEW TASK'}</p><h2>{task.id ? 'Refine your plan' : 'Plan a study task'}</h2><label>Title<input required value={form.title || ''} onChange={e => change('title', e.target.value)} placeholder="e.g. Solve Electrostatics PYQs"/></label><div className="editor-grid"><label>Subject<select value={form.subject || 'General'} onChange={e => change('subject', e.target.value)}><option>Physics</option><option>Chemistry</option><option>Mathematics</option><option>General</option></select></label><label>Priority<select value={form.priority || 'medium'} onChange={e => change('priority', e.target.value)}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Chapter<input value={form.chapter || ''} onChange={e => change('chapter', e.target.value)} placeholder="Optional"/></label><label>Time (minutes)<input type="number" min="5" value={form.estimated_minutes || 60} onChange={e => change('estimated_minutes', Number(e.target.value))}/></label><label>Deadline<input type="date" value={form.deadline || ''} onChange={e => change('deadline', e.target.value)}/></label><label>Repeat<select value={form.recurrence || 'none'} onChange={e => change('recurrence', e.target.value)}><option value="none">Does not repeat</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label></div><label>Notes<textarea value={form.notes || ''} onChange={e => change('notes', e.target.value)} placeholder="Optional reminders or approach"/></label><div className="editor-actions"><button type="button" onClick={close}>Cancel</button><button className="task-create" disabled={saving}>{saving ? 'Saving…' : 'Save task'}</button></div></form></div> }
